package rfidLeitor;

import com.alien.enterpriseRFID.reader.AlienReaderException;

import java.io.IOException;

import javax.swing.JFrame;
import javax.swing.JLabel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author guilhermehenrique
 */
public class Tp1IotMainJFrame extends javax.swing.JFrame {
	
	
	Tp1IotReader reader;
	javax.swing.table.DefaultTableModel model;
	DialogConfig dialogConfig;
	
    /**
     * Creates new form tp1IotMainJFrame
     */
    public Tp1IotMainJFrame() throws AlienReaderException {
    	reader = new Tp1IotReader();
    	
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "serial" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jInternalFrame1 = new javax.swing.JInternalFrame();
        labelModo = new javax.swing.JLabel();
        comboBoxModo = new javax.swing.JComboBox<>();
        labelEfeito = new javax.swing.JLabel();
        comboBoxEfeito = new javax.swing.JComboBox<>();
        labelTimeOut = new javax.swing.JLabel();
        textfieldTimeOut = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        buttonIniciar = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        buttonParar = new javax.swing.JButton();
        buttonConfig = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        textFieldDistancia = new javax.swing.JTextField();

        jInternalFrame1.setVisible(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelModo.setText("Modo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 14, 0, 0);
        getContentPane().add(labelModo, gridBagConstraints);

        comboBoxModo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "autonomo" }));
        comboBoxModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxModoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 18, 0, 0);
        getContentPane().add(comboBoxModo, gridBagConstraints);

        labelEfeito.setText("Efeito:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 21, 0, 0);
        getContentPane().add(labelEfeito, gridBagConstraints);

        comboBoxEfeito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "Água", "Metal" }));
        comboBoxEfeito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEfeitoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 11, 0, 0);
        getContentPane().add(comboBoxEfeito, gridBagConstraints);

        labelTimeOut.setText("Time out");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 0, 0);
        getContentPane().add(labelTimeOut, gridBagConstraints);

        textfieldTimeOut.setToolTipText("2");
        textfieldTimeOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldTimeOutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 18, 0, 0);
        getContentPane().add(textfieldTimeOut, gridBagConstraints);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"000",  new Float(0.0),  new Float(0.0),  new Float(0.0),  new Float(0.0),  new Float(0.0)}
            },
            new String [] {
                "ID", "Distância Máxima ", "Taxa de Leitura (Min)", "Taxa de Leitura (Max)", "Taxa de Leitura (Media)", "Desvio Padrão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableData);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1148;
        gridBagConstraints.ipady = 321;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(49, 14, 0, 17);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel1.setText("INTERNET DAS COISAS - TRABALHO PRÁTICO 1 ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 14, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("MEDIÇÕES DE RFID - ALIEN 9650");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 14, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("GRUPO: Andre, Guilherme Henrique e Gilson");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 14, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLayeredPane2.setLayout(new java.awt.GridLayout(1, 0));

        buttonIniciar.setText("Inciar");
        buttonIniciar.setActionCommand("Iniciar");
        buttonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					buttonIniciarActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (AlienReaderException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        jLayeredPane2.add(buttonIniciar);

        buttonCancel.setText("Cancela");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        jLayeredPane2.add(buttonCancel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.ipadx = 989;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 14, 27, 17);
        getContentPane().add(jLayeredPane2, gridBagConstraints);

        buttonParar.setText("Parar");
        buttonParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPararActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 58, 0, 0);
        getContentPane().add(buttonParar, gridBagConstraints);

        buttonConfig.setText("Configuração");
        buttonConfig.setToolTipText("");
        buttonConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfigActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 87, 0, 17);
        getContentPane().add(buttonConfig, gridBagConstraints);

        jLabel4.setText("Distancia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 62, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 12, 0, 0);
        getContentPane().add(textFieldDistancia, gridBagConstraints);

        setBounds(0, 0, 1206, 636);
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxModoActionPerformed(java.awt.event.ActionEvent evt) {                                             
    	
    	reader.setModo(comboBoxModo.getSelectedItem().toString());
    }

    private void comboBoxEfeitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEfeitoActionPerformed
    	
    	reader.setEfeito(comboBoxEfeito.getSelectedItem().toString());
        
    }//GEN-LAST:event_comboBoxEfeitoActionPerformed

    private void buttonIniciarActionPerformed(java.awt.event.ActionEvent evt) throws IOException, AlienReaderException {//GEN-FIRST:event_buttonIniciarActionPerformed
        // TODO add your handling code here:
    	reader.setCaminholog(dialogConfig.getjTextFieldLog().getText());
    	reader.setIpLeitor(dialogConfig.getjTextFieldIp().getText());
    	reader.setUsernameLeitor(dialogConfig.getjTextFieldUser().getText());
    	reader.setPassWordLeitor(dialogConfig.getjPasswordFieldPass().getText());
    	reader.setDistancia(this.textFieldDistancia.getText());
    	
        if (this.comboBoxModo.getSelectedItem().toString() == "Ativo") {
        	
        	reader.setPortaLeitor(Integer.parseInt(dialogConfig.getjTextFieldActPort().getText()));
        	
			Thread t = new Thread() {
				
				public void run() {
		    		buttonIniciar.setEnabled(false);
		    		
		    		try {
						reader.lerAtivamente();
					} catch (AlienReaderException e) {
						e.printStackTrace();
					} catch (IOException e) {
						e.printStackTrace();
					}
		    		
		            Item[] tags = reader.getResults();
		            
		            int numTags  = reader.numTags();
		            int rowCount = model.getRowCount();
		            
		            for (int i = 0; i < rowCount; i++) {
		            	
		            	model.removeRow(0);
		            	
		            }
		            
		            model.fireTableStructureChanged();
		            
		            for(Item tag : tags) {
		            	
		            	model.addRow(new Object[] {tag.id, tag.antenna, tag.reads, tag.distanceReal, tag.distanceEst, tag.rssi });
		            	
		            }
		            
		            buttonIniciar.setEnabled(true);
				}
			};
			t.start();
		    
		} else {
			
			Thread t = new Thread() {
				public void run() {
					
					buttonIniciar.setEnabled(false);
					
					try {
						reader.lerAuto();
					} catch (IOException | AlienReaderException | InterruptedException e) {}
					
		    		/*long timeout = Long.parseLong(textfieldTimeOut.getText());
		    		
		    		if (!textfieldTimeOut.getText().isEmpty() &&  timeout > 0) {

		    			long startTimeUser = System.currentTimeMillis();
		    			
		    			while ((System.currentTimeMillis() - startTimeUser) < (timeout * 1000)){
		    				
		    				try {
								reader.lerAtivamente();
							} catch (AlienReaderException e) {
								e.printStackTrace();
							} catch (IOException e) {
								e.printStackTrace();
							}
		    				
		                    Item[] tags = reader.getResults();
		                    
		                    int numTags  = reader.numTags();
		                    int rowCount = model.getRowCount();
		                    
		                    for (int i = 0; i < rowCount; i++) {
		                    	
		                    	model.removeRow(0);
		                    	
		                    }
		                    
		                    model.fireTableStructureChanged();
		                    
		                    for(Item tag : tags) {
		                    	
		                    	model.addRow(new Object[] {tag.id, tag.antenna, tag.reads, tag.distanceReal, tag.distanceEst, tag.rssi });
		                    	
		                    }
		          
		    			}
		    		}
		    		*/
		    		
		    		buttonIniciar.setEnabled(true);
				}
			};
			t.start();
			
		}
    }//GEN-LAST:event_buttonIniciarActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {
    	System.exit(0);
    }

    private void textfieldTimeOutActionPerformed(java.awt.event.ActionEvent evt) {
    		
    }

    private void buttonPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPararActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPararActionPerformed

    private void buttonConfigActionPerformed(java.awt.event.ActionEvent evt) {                                             
   
	    dialogConfig.setVisible(true);
	    dialogConfig.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);

    }

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonConfig;
    private javax.swing.JButton buttonIniciar;
    private javax.swing.JButton buttonParar;
    private javax.swing.JComboBox<String> comboBoxEfeito;
    private javax.swing.JComboBox<String> comboBoxModo;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEfeito;
    private javax.swing.JLabel labelModo;
    private javax.swing.JLabel labelTimeOut;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField textFieldDistancia;
    private javax.swing.JTextField textfieldTimeOut;
    // End of variables declaration//GEN-END:variables
}
